export const SET_AUTOBOT = 'SET_AUTOBOT'
export const SET_LAUCH_INFO  ='SET_LAUCH_INFO'
export const SET_AUTOBOT_START = 'SET_AUTOBOT_START'
export const SET_AUTOBOT_STOP = 'SET_AUTOBOT_STOP'
export const SET_AUTOBOT_COLLECTED = 'SET_AUTOBOT_COLLECTED' 

export const SET_AUTOBOT_READY_TO_LAUNCH = 'SET_AUTOBOT_READY_TO_LAUNCH'
export const SET_AUTOBOT_READY_TO_COLLECT = 'SET_AUTOBOT_READY_TO_COLLECT'
export const SET_AUTOBOT_LAST_LAUNCH_TIME = 'SET_AUTOBOT_LAST_LAUNCH_TIME'

export const UPDATE_AUTOBOT_LEVEL = 'UPDATE_AUTOBOT_LEVEL'